# Generated by Django 5.2.8 on 2025-11-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_book_read_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_to_read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Romance', 'Romance'), ('Science', 'Science'), ('Thriller', 'Thriller'), ('Biography', 'Biography'), ('Self-Help', 'Self-Help'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Poetry', 'Poetry')], max_length=11)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('cover_image', models.URLField()),
            ],
        ),
    ]
