# Generated by Django 5.2.8 on 2025-11-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_book_to_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_to_read',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='book_to_read',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='book_to_read',
            name='rating',
        ),
        migrations.AddField(
            model_name='book_to_read',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a detailed description of the item.', null=True),
        ),
    ]
