# Generated by Django 5.2.8 on 2025-11-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_book_to_read_date_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_read',
            name='cover_image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='book_to_read',
            name='cover_image',
            field=models.URLField(max_length=1000),
        ),
    ]
