# Generated by Django 5.2.8 on 2025-11-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_book_read_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoute', models.TextField(blank=True, help_text='Qoute worth remebering is...', null=True)),
                ('author', models.CharField(max_length=100)),
                ('book', models.CharField(max_length=100)),
            ],
        ),
    ]
