# Generated by Django 5.2.8 on 2025-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='qoute',
        ),
        migrations.AddField(
            model_name='quotes',
            name='quote',
            field=models.TextField(blank=True, help_text='Quote worth remebering is...', null=True),
        ),
    ]
